version: '3.3'

services:
  redis:
    image: redis:7.0
    volumes:
      - redisdata:/data

  bot:
    build:
      context: ./bot
    env_file:
      - ./bot/.env
    depends_on:
      - redis


volumes:
  redisdata: